apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.depName }}
  name: {{ .Values.depName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.podName }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.podName }}
    spec:
      containers:
        - image: {{ .Values.imageName }}
          name: {{ .Values.containerName }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
          {{- range .Values.containerEnvVar}}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end}}
          resources:
            limits:
              memory: 400Mi
              cpu: 150m
            requests:
              cpu: 70m
              memory: 200Mi
