apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.podName }}
  type: {{ .Values.serviceType }}