depName: kafka-dep
replicasNum: 1
podName: kafka-pod
imageName: wurstmeister/kafka
containerName: kafka-container
containerPort: 9092
containerEnvVar:
  - name:  KAFKA_ZOOKEEPER_CONNECT
    value: "zookeeper-svc:2181"
  - name:  KAFKA_ADVERTISED_HOST_NAME
    value: "kafka-svc"
  - name:  KAFKA_CREATE_TOPICS
    value: "R1"
serviceName: kafka-svc
servicePort: 9092