depName: product-service-dep
replicasNum: 1
podName: product-service-pod
imageName: soulaimandockerhub/ecom-backend-product-service
imageVersion: secured-v1.1
containerName: product-service-container
containerPort: 8080
containerEnvVar:
  - name: MONGODB_HOST
    value: "mongodb-svc"
  - name: MONGODB_PORT
    value: "27017"
  - name: SERVER_PORT
    value: "8080"
  - name: MONGODB_USERNAME
    value: "admin"
  - name: MONGODB_PASSWORD
    value: "password"
  - name: BOOTSRAP_KAFKA_SERVER
    value: "kafka-svc"
  - name: BOOTSRAP_KAFKA_PORT
    value: "9092"
  - name: KEYCLOAK_SERVER
    value: "http://10.10.9.133:30080"
  - name: KEYCLOAK_REALM
    value: "ecom-realm"
  - name: KEYCLOAK_CLIENT
    value: "ecom-app"
serviceName: product-service-svc
servicePort: 8080
serviceType: NodePort
nodePort: 30010